project:
  name: # project name which is namespace prefix like "Demo/Model/TableName"
    Demo
cache:
  engine:
    memcached
  prefix:
    prefix_
  expire:
    300
db:
  engine:
    mysql
log:
  dir:
    /../Logs/
  level:
    0